# Generated by Django 3.2.5 on 2021-07-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='', max_length=70)),
                ('last', models.CharField(default='', max_length=70)),
                ('email_id', models.EmailField(max_length=250)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
